language: python
python:
  - "3.4"
  - "3.5"

install:
  - pip install leveldb
  - pip install pytest-cov coveralls

script:
  coverage run --source=levelpy setup.py pytest --addopts '--cov=levelpy.view --cov-report=term-missing'

after_success:
  coveralls
