language: python
python:
  - "3.4"
  - "3.5"

install:
  - pip install leveldb
  - pip install pytest pytest-cov
  - pip install python-coveralls

script:
  - python setup.py pytest --addopts ' --cov=levelpy --cov-report=term-missing -v'
#
# after_success:
#   coveralls
# script:
#     - py.test tests --cov=levelpy --cov-report=term-missing -v

after_success:
    - coveralls
